services:

  server:
    build:
      context: .
      dockerfile: Dockerfile.server

    container_name: careergps-server

    env_file:
      - apps/server/.env

    ports:
      - "3000:3000"

    restart: unless-stopped


  web:
    build:
      context: .
      dockerfile: Dockerfile.web

    container_name: careergps-web

    env_file:
      - apps/web/.env

    ports:
      - "5173:5173"

    depends_on:
      - server

    restart: unless-stopped