import express from "express";
import { db } from "@/db";
import { calendarEvents } from "../db/schema";
import { user } from "@/modules/user/db/schema";
import { skillCurriculumNodes } from "@/modules/skills/db/curriculum_schema";
import { roadmapNodes } from "@/modules/roadmap/db/schema";
import { eq, inArray, and, asc } from "drizzle-orm";
import * as ics from "ics";

const router: express.Router = express.Router();

router.get("/feed/:token.ics", async (req, res) => {
    try {
        const { token } = req.params;

        // Find user by token
        const userRecord = await db.query.user.findFirst({
            where: eq(user.calendarSyncToken, token)
        });

        if (!userRecord) {
            return res.status(404).send("Calendar feed not found");
        }

        // Fetch user's scheduled/in progress calendar events
        const events = await db
            .select({
                id: calendarEvents.id,
                date: calendarEvents.date,
                startTime: calendarEvents.startTime,
                endTime: calendarEvents.endTime,
                status: calendarEvents.status,
                roadmapNodeId: calendarEvents.roadmapNodeId,
                title: skillCurriculumNodes.title,
                description: skillCurriculumNodes.description,
            })
            .from(calendarEvents)
            .innerJoin(roadmapNodes, eq(calendarEvents.roadmapNodeId, roadmapNodes.id))
            .innerJoin(skillCurriculumNodes, eq(roadmapNodes.curriculumNodeId, skillCurriculumNodes.id))
            .where(
                and(
                    eq(calendarEvents.userId, userRecord.id),
                    inArray(calendarEvents.status, ["scheduled", "completed"])
                )
            )
            .orderBy(asc(calendarEvents.date), asc(calendarEvents.startTime));

        const icsEvents: ics.EventAttributes[] = events.map(ev => {
            const dateParts = ev.date.split("-").map(Number);
            const startParts = ev.startTime.split(":").map(Number);
            const endParts = ev.endTime.split(":").map(Number);

            const year = dateParts[0] as number;
            const month = dateParts[1] as number;
            const day = dateParts[2] as number;
            const startHour = startParts[0] as number;
            const startMinute = startParts[1] as number;
            const endHour = endParts[0] as number;
            const endMinute = endParts[1] as number;

            return {
                start: [year, month, day, startHour, startMinute],
                end: [year, month, day, endHour, endMinute],
                title: `${ev.status === "completed" ? "✅ " : ""}${ev.title || "Learning Session"}`,
                description: ev.description || "Learning session generated by AI",
                status: "CONFIRMED",
                busyStatus: "BUSY",
                uid: ev.id,
            };
        });

        if (icsEvents.length === 0) {
            // Return empty calendar if no events
            const { error, value } = ics.createEvents([{
                start: [new Date().getFullYear(), new Date().getMonth() + 1, new Date().getDate(), 12, 0],
                duration: { hours: 1 },
                title: "Calendar Connected",
                description: "Your learning calendar is connected but currently empty. Generate a schedule to see events here.",
            }]);
            
            if (error || !value) {
                return res.status(500).send("Error generating empty calendar");
            }

            res.setHeader("Content-Type", "text/calendar; charset=utf-8");
            res.setHeader("Content-Disposition", 'attachment; filename="calendar.ics"');
            return res.send(value);
        }

        const { error, value } = ics.createEvents(icsEvents);

        if (error || !value) {
            console.error("Error generating ICS:", error);
            return res.status(500).send("Error generating calendar");
        }

        res.setHeader("Content-Type", "text/calendar; charset=utf-8");
        res.setHeader("Content-Disposition", 'attachment; filename="calendar.ics"');
        return res.send(value);

    } catch (error) {
        console.error("Calendar feed error:", error);
        res.status(500).send("Internal Server Error");
    }
});

export default router;
